import { GoogleGenAI } from "@google/genai";
import type { NextRequest } from "next/server";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Shape of the JSON body we expect from the client on POST.
 * `content` is the raw product-page text the user wants analyzed.
 */
interface GeoCheckRequestBody {
  content: string;
}

/** One row of the GEO checklist: a factor, whether it passed, and why. */
interface GeoChecklistItem {
  factor: string;
  pass: boolean;
  explanation: string;
}

/**
 * Shape of the payload we ask Gemini to return, and the shape we send back to
 * the client on success. Keeping it as an interface means TypeScript flags us
 * if we ever forget a key when validating the model's output.
 */
interface GeoCheckResponse {
  overallScore: number; // 0–100
  checklist: GeoChecklistItem[];
}

// ---------------------------------------------------------------------------
// Gemini client setup
// ---------------------------------------------------------------------------

// The current GA "flash" model as of the @google/genai unified SDK. Flash is
// the fast/cheap tier — a good fit for short structured generations like this.
const GEMINI_MODEL = "gemini-3.6-flash";

// The exact GEO factors we ask the model to evaluate. Listing them here keeps
// the prompt and the client checklist in sync and gives us something concrete
// to validate the response against.
const GEO_FACTORS = [
  "Clear entity/product naming",
  "Question-and-answer phrasing",
  "Factual specificity (specs, numbers)",
  "Structured/scannable formatting",
  "Comparison context",
  "Semantic clarity for AI parsing",
] as const;

// ---------------------------------------------------------------------------
// Route handler
// ---------------------------------------------------------------------------

/**
 * POST /api/geo-check
 *
 * Accepts pasted product-page content and returns a GEO (Generative Engine
 * Optimization) readiness score plus a pass/fail checklist, generated by Gemini.
 * Everything runs on the server, so the API key is never exposed to the browser.
 */
export async function POST(request: NextRequest) {
  // --- 1. Make sure the API key is configured -----------------------------
  // We read the key at request time (not module load) so a missing key gives
  // a clean 500 instead of crashing the whole server on startup.
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return Response.json(
      { error: "Server is missing GEMINI_API_KEY configuration." },
      { status: 500 },
    );
  }

  // --- 2. Parse and validate the incoming request body --------------------
  // request.json() throws if the body isn't valid JSON, so we guard it.
  let body: GeoCheckRequestBody;
  try {
    body = await request.json();
  } catch {
    return Response.json(
      { error: "Request body must be valid JSON." },
      { status: 400 },
    );
  }

  const { content } = body;

  // Content must be a present, non-empty string. Bad input = 400, not 500.
  if (typeof content !== "string" || !content.trim()) {
    return Response.json(
      { error: "Missing or invalid field. Expected a non-empty string: content." },
      { status: 400 },
    );
  }

  // --- 3. Build the prompt ------------------------------------------------
  // The system instruction sets the model's persona; the prompt carries the
  // pasted content plus the exact output contract we need back.
  const systemInstruction =
    "You are an expert in Generative Engine Optimization (GEO) — optimizing " +
    "web content so AI answer engines like ChatGPT, Perplexity, and Google AI " +
    "Overviews are likely to surface and cite it. You analyze content honestly " +
    "and score it against concrete, well-understood GEO best practices.";

  const prompt = `Analyze the following product page content for GEO readiness —
how likely AI answer engines are to surface and cite it.

Evaluate it against EXACTLY these ${GEO_FACTORS.length} factors, in this order:
${GEO_FACTORS.map((f, i) => `${i + 1}. ${f}`).join("\n")}

For each factor, decide pass (true) or fail (false) and give a one-line
explanation. Then give an overall GEO readiness score from 0 to 100.

Content to analyze:
"""
${content}
"""

Respond ONLY with a JSON object using EXACTLY these keys (no markdown, no commentary):
{
  "overallScore": number,
  "checklist": [
    { "factor": string, "pass": boolean, "explanation": string }
  ]
}
The "checklist" array must contain one item per factor listed above, using the
factor names verbatim.`;

  // --- 4. Call Gemini -----------------------------------------------------
  // We ask for a JSON mime type so the model returns raw JSON rather than
  // prose wrapped in markdown fences. Network/SDK errors are caught below.
  let rawText: string | undefined;
  try {
    const ai = new GoogleGenAI({ apiKey });
    const result = await ai.models.generateContent({
      model: GEMINI_MODEL,
      contents: prompt,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
      },
    });

    // `.text` concatenates all text parts of the first candidate.
    rawText = result.text;
  } catch (err) {
    // Anything from the SDK (bad key, quota, network) lands here.
    console.error("Gemini request failed:", err);
    return Response.json(
      { error: "Failed to reach the AI service. Please try again later." },
      { status: 502 },
    );
  }

  if (!rawText) {
    return Response.json(
      { error: "The AI service returned an empty response." },
      { status: 502 },
    );
  }

  // --- 5. Parse and validate the model output -----------------------------
  // Even with JSON mode, models can occasionally emit stray text or fences,
  // so we defensively strip a fenced code block before parsing, and wrap the
  // whole thing in try/catch so malformed output never crashes the route.
  let parsed: GeoCheckResponse;
  try {
    const cleaned = rawText
      .trim()
      .replace(/^```(?:json)?\s*/i, "") // drop a leading ```json fence if present
      .replace(/\s*```$/i, "") // drop a trailing ``` fence if present
      .trim();

    const data = JSON.parse(cleaned) as Partial<GeoCheckResponse>;

    // The score must be a finite number, and the checklist must be a non-empty
    // array of well-formed items. Anything else = malformed output.
    if (
      typeof data.overallScore !== "number" ||
      !Number.isFinite(data.overallScore) ||
      !Array.isArray(data.checklist) ||
      data.checklist.length === 0 ||
      !data.checklist.every(
        (item) =>
          item !== null &&
          typeof item === "object" &&
          typeof item.factor === "string" &&
          typeof item.pass === "boolean" &&
          typeof item.explanation === "string",
      )
    ) {
      throw new Error("Response JSON is missing required keys.");
    }

    parsed = {
      // Clamp and round the score so the UI always shows a clean 0–100 integer.
      overallScore: Math.max(0, Math.min(100, Math.round(data.overallScore))),
      checklist: data.checklist.map((item) => ({
        factor: item.factor,
        pass: item.pass,
        explanation: item.explanation,
      })),
    };
  } catch (err) {
    console.error("Failed to parse Gemini output:", err, "\nRaw:", rawText);
    return Response.json(
      { error: "The AI service returned malformed output. Please try again." },
      { status: 502 },
    );
  }

  // --- 6. Success ---------------------------------------------------------
  return Response.json(parsed, { status: 200 });
}
