import { GoogleGenAI } from "@google/genai";
import type { NextRequest } from "next/server";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Shape of the JSON body we expect from the client on POST.
 * The three product fields are required strings; `tone` is optional.
 */
interface OptimizeRequestBody {
  productName: string;
  details: string;
  rawDescription: string;
  tone?: string; // optional brand tone; validated against ALLOWED_TONES below
}

/**
 * Shape of the SEO payload we ask Gemini to return, and the shape we send
 * back to the client on success. Keeping this as an interface means TypeScript
 * will flag us if we ever forget a key when validating the model's output.
 */
interface OptimizeResponse {
  optimizedDescription: string;
  metaTitle: string;
  metaDescription: string;
  openGraph: {
    ogTitle: string;
    ogDescription: string;
  };
}

// ---------------------------------------------------------------------------
// Gemini client setup
// ---------------------------------------------------------------------------

// The current GA "flash" model as of the @google/genai unified SDK. Flash is
// the fast/cheap tier — a good fit for short structured generations like this.
const GEMINI_MODEL = "gemini-3.6-flash";

// Brand tones the client may request. Must stay in sync with the selector in
// src/app/page.tsx. The first entry is the default/fallback.
const ALLOWED_TONES = [
  "Professional",
  "Playful",
  "Luxury",
  "Technical",
] as const;
type Tone = (typeof ALLOWED_TONES)[number];
const DEFAULT_TONE: Tone = "Professional";

/**
 * Normalize an incoming tone value: return it only if it's one of the allowed
 * tones, otherwise fall back to the default. Missing/invalid input is safe.
 */
function resolveTone(value: unknown): Tone {
  return ALLOWED_TONES.includes(value as Tone) ? (value as Tone) : DEFAULT_TONE;
}

// Short, human-readable guidance injected into the prompt for each tone.
const TONE_GUIDANCE: Record<Tone, string> = {
  Professional:
    "polished, credible, and business-appropriate; clear and confident without hype",
  Playful:
    "fun, upbeat, and conversational; light humor and energetic phrasing are welcome",
  Luxury:
    "elegant, aspirational, and refined; evoke premium quality and exclusivity",
  Technical:
    "precise and detail-oriented; emphasize specifications, materials, and measurable benefits",
};

// ---------------------------------------------------------------------------
// Route handler
// ---------------------------------------------------------------------------

/**
 * POST /api/optimize
 *
 * Accepts a product and returns SEO-optimized copy generated by Gemini.
 * Everything runs on the server, so the API key is never exposed to the browser.
 */
export async function POST(request: NextRequest) {
  // --- 1. Make sure the API key is configured -----------------------------
  // We read the key at request time (not module load) so a missing key gives
  // a clean 500 instead of crashing the whole server on startup.
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return Response.json(
      { error: "Server is missing GEMINI_API_KEY configuration." },
      { status: 500 },
    );
  }

  // --- 2. Parse and validate the incoming request body --------------------
  // request.json() throws if the body isn't valid JSON, so we guard it.
  let body: OptimizeRequestBody;
  try {
    body = await request.json();
  } catch {
    return Response.json(
      { error: "Request body must be valid JSON." },
      { status: 400 },
    );
  }

  const { productName, details, rawDescription } = body;

  // Tone is optional: resolve to an allowed value, defaulting to Professional
  // when it's missing or unrecognized so older clients keep working unchanged.
  const tone = resolveTone(body.tone);

  // Every field must be a present, non-empty string. Bad input = 400, not 500.
  if (
    typeof productName !== "string" ||
    typeof details !== "string" ||
    typeof rawDescription !== "string" ||
    !productName.trim() ||
    !details.trim() ||
    !rawDescription.trim()
  ) {
    return Response.json(
      {
        error:
          "Missing or invalid fields. Expected non-empty strings: productName, details, rawDescription.",
      },
      { status: 400 },
    );
  }

  // --- 3. Build the prompt ------------------------------------------------
  // The system instruction sets the model's persona; the prompt carries the
  // actual product data plus the exact output contract we need back.
  const systemInstruction =
    "You are an expert e-commerce SEO copywriter. You write compelling, " +
    "keyword-rich product copy that ranks well in search engines while " +
    "staying accurate to the product's real features.";

  const prompt = `Optimize the following product for SEO.

Product name: ${productName}
Key details: ${details}
Raw description: ${rawDescription}

Write all copy in a ${tone} brand tone — ${TONE_GUIDANCE[tone]}.

Produce:
1. An SEO-optimized product description (persuasive, keyword-rich, 2-4 short paragraphs).
2. An SEO meta title (<= 60 characters).
3. An SEO meta description (<= 160 characters).
4. Open Graph tags for social sharing.

Respond ONLY with a JSON object using EXACTLY these keys (no markdown, no commentary):
{
  "optimizedDescription": string,
  "metaTitle": string,
  "metaDescription": string,
  "openGraph": {
    "ogTitle": string,
    "ogDescription": string
  }
}`;

  // --- 4. Call Gemini -----------------------------------------------------
  // We ask for a JSON mime type so the model returns raw JSON rather than
  // prose wrapped in markdown fences. Network/SDK errors are caught below.
  let rawText: string | undefined;
  try {
    const ai = new GoogleGenAI({ apiKey });
    const result = await ai.models.generateContent({
      model: GEMINI_MODEL,
      contents: prompt,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
      },
    });

    // `.text` concatenates all text parts of the first candidate.
    rawText = result.text;
  } catch (err) {
    // Anything from the SDK (bad key, quota, network) lands here.
    console.error("Gemini request failed:", err);
    return Response.json(
      { error: "Failed to reach the AI service. Please try again later." },
      { status: 502 },
    );
  }

  if (!rawText) {
    return Response.json(
      { error: "The AI service returned an empty response." },
      { status: 502 },
    );
  }

  // --- 5. Parse and validate the model output -----------------------------
  // Even with JSON mode, models can occasionally emit stray text or fences,
  // so we defensively strip a fenced code block before parsing, and wrap the
  // whole thing in try/catch so malformed output never crashes the route.
  let parsed: OptimizeResponse;
  try {
    const cleaned = rawText
      .trim()
      .replace(/^```(?:json)?\s*/i, "") // drop a leading ```json fence if present
      .replace(/\s*```$/i, "") // drop a trailing ``` fence if present
      .trim();

    const data = JSON.parse(cleaned) as Partial<OptimizeResponse>;

    // Confirm every expected key exists and has the right type. If the model
    // renamed or dropped a key, treat it as malformed rather than shipping
    // an incomplete object to the client.
    if (
      typeof data.optimizedDescription !== "string" ||
      typeof data.metaTitle !== "string" ||
      typeof data.metaDescription !== "string" ||
      typeof data.openGraph !== "object" ||
      data.openGraph === null ||
      typeof data.openGraph.ogTitle !== "string" ||
      typeof data.openGraph.ogDescription !== "string"
    ) {
      throw new Error("Response JSON is missing required keys.");
    }

    parsed = {
      optimizedDescription: data.optimizedDescription,
      metaTitle: data.metaTitle,
      metaDescription: data.metaDescription,
      openGraph: {
        ogTitle: data.openGraph.ogTitle,
        ogDescription: data.openGraph.ogDescription,
      },
    };
  } catch (err) {
    console.error("Failed to parse Gemini output:", err, "\nRaw:", rawText);
    return Response.json(
      { error: "The AI service returned malformed output. Please try again." },
      { status: 502 },
    );
  }

  // --- 6. Success ---------------------------------------------------------
  return Response.json(parsed, { status: 200 });
}
